### PR TITLE
Dokker 

### PR DESCRIPTION
**Pull request by Darkdeath-2**
Auto murge

### CODE REVIEW

**Comment by Darkdeath-2** [comment]
https://github.com/docker/getting-started/pull/232#issue-1075247189

**Review by Darkdeath-2 — COMMENTED** [review]
Yes that work

**Comment by Darkdeath-2** [comment]
From a2932698bd96021722e7187800692ad087cf6901 Mon Sep 17 00:00:00 2001
From: spicylentils <71917720+spicylentils@users.noreply.github.com>
Date: Mon, 28 Sep 2020 17:01:39 -0700
Subject: [PATCH 01/20] Update docs/tutorial/using-bind-mounts/index.md

Fix confusing wording regarding sources and destinations
---
 docs/tutorial/using-bind-mounts/index.md | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/docs/tutorial/using-bind-mounts/index.md b/docs/tutorial/using-bind-mounts/index.md
index 072f32cd..a645161d 100644
--- a/docs/tutorial/using-bind-mounts/index.md
+++ b/docs/tutorial/using-bind-mounts/index.md
@@ -55,8 +55,8 @@ So, let's do it!
     ```
 
     - `-dp 3000:3000` - same as before. Run in detached (background) mode and create a port mapping
-    - `-w /app` - sets the "working directory" or the current directory that the command will run from
-    - `-v "$(pwd):/app"` - bind mount the current directory from the host in the container into the `/app` directory
+    - `-w /app` - sets the container's present working directory where the command will run from
+    - `-v "$(pwd):/app"` - bind mount (link) the host's present working directory to the container's `/app` directory
     - `node:12-alpine` - the image to use. Note that this is the base image for our app from the Dockerfile
     - `sh -c "yarn install && yarn run dev"` - the command. We're starting a shell using `sh` (alpine doesn't have `bash`) and
       running `yarn install` to install _all_ dependencies and then running `yarn run dev`. If we look in the `package.json`,

From e9f8d4443a88221402f740603114f8fa1bf9657b Mon Sep 17 00:00:00 2001
From: Telescu Nicolae <36912215+NicolaeTelescu@users.noreply.github.com>
Date: Wed, 20 Jan 2021 11:06:02 +0200
Subject: [PATCH 02/20] Update index.md

The command for bind mount doesn't run in Ubuntu if the user is not in the source code folder. At least, for me didn't work. So I specified that to prevent errors and bugs.
---
 docs/tutorial/using-bind-mounts/index.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/docs/tutorial/using-bind-mounts/index.md b/docs/tutorial/using-bind-mounts/index.md
index 072f32cd..11aa0ca2 100644
--- a/docs/tutorial/using-bind-mounts/index.md
+++ b/docs/tutorial/using-bind-mounts/index.md
@@ -36,7 +36,7 @@ So, let's do it!
 
 1. Make sure you don't have any previous `getting-started` containers running.
 
-1. Run the following command. We'll explain what's going on afterwards:
+1. Run the following command from the source code folder. We'll explain what's going on afterwards:
 
     ```bash
     docker run -dp 3000:3000 \

From dcfbefe0af2799e8d5e74b761dc96956cf955100 Mon Sep 17 00:00:00 2001
From: Pankaj Patil <pankaj.patil2099@hotmail.com>
Date: Fri, 12 Feb 2021 23:26:42 +0530
Subject: [PATCH 03/20] Point To The Correct Link For Play With Docker

---
 docs/tutorial/sharing-our-app/index.md | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/docs/tutorial/sharing-our-app/index.md b/docs/tutorial/sharing-our-app/index.md
index 6cbb0721..42a12f93 100644
--- a/docs/tutorial/sharing-our-app/index.md
+++ b/docs/tutorial/sharing-our-app/index.md
@@ -58,7 +58,7 @@ an example command that you will need to run to push to this repo.
 Now that our image has been built and pushed into a registry, let's try running our app on a brand
 new instance that has never seen this container image! To do this, we will use Play with Docker.
 
-1. Open your browser to [Play with Docker](http://play-with-docker.com).
+1. Open your browser to [Play with Docker](https://labs.play-with-docker.com/).
 
 1. Log in with your Docker Hub account.
 
@@ -89,4 +89,4 @@ can use the latest version of the image.
 Now that we have that figured out, let's circle back around to what we noticed at the end of the last
 section. As a reminder, we noticed that when we restarted the app, we lost all of our todo list items.
 That's obviously not a great user experience, so let's learn how we can persist the data across 
-restarts!
\ No newline at end of file
+restarts!

From dbae842f9cef9153452c20a7c3d999e47d13da3e Mon Sep 17 00:00:00 2001
From: Moses <47298076+mo5e5@users.noreply.github.com>
Date: Tue, 2 Mar 2021 07:51:54 +0200
Subject: [PATCH 04/20] Period omission at the end of line 7,8 and 10. The
 suggested bullet sign used "- " does not display

Am using google chrome browser Version 88.0.4324.190 (Official Build) (64-bit)
---
 docs/tutorial/multi-container-apps/index.md | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/docs/tutorial/multi-container-apps/index.md b/docs/tutorial/multi-container-apps/index.md
index 68a0ed05..20d3ca46 100644
--- a/docs/tutorial/multi-container-apps/index.md
+++ b/docs/tutorial/multi-container-apps/index.md
@@ -4,12 +4,12 @@ application stack. The following question often arises - "Where will MySQL run?
 container or run it separately?" In general, **each container should do one thing and do it well.** A few
 reasons:
 
-- There's a good chance you'd have to scale APIs and front-ends differently than databases
-- Separate containers let you version and update versions in isolation
+- There's a good chance you'd have to scale APIs and front-ends differently than databases.
+- Separate containers let you version and update versions in isolation.
 - While you may use a container for the database locally, you may want to use a managed service
   for the database in production. You don't want to ship your database engine with your app then.
 - Running multiple processes will require a process manager (the container only starts one process), 
-  which adds complexity to container startup/shutdown
+  which adds complexity to container startup/shutdown.
 
 And there are more reasons. So, we will update our application to work like this:
 

From 5d5e551104a5a2c759cf3ded29a49fb05631f2d9 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Ant=C3=B3nio=20Alvarenga?= <antonioalvarengavd@gmail.com>
Date: Fri, 7 May 2021 11:26:18 +0100
Subject: [PATCH 05/20] Multi-container apps: add workaround for non amd64
 machines

---
 docs/tutorial/multi-container-apps/index.md | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/docs/tutorial/multi-container-apps/index.md b/docs/tutorial/multi-container-apps/index.md
index 68a0ed05..3781ef16 100644
--- a/docs/tutorial/multi-container-apps/index.md
+++ b/docs/tutorial/multi-container-apps/index.md
@@ -66,6 +66,11 @@ For now, we will create the network first and attach the MySQL container at star
         You'll notice we're using a volume named `todo-mysql-data` here and mounting it at `/var/lib/mysql`, which is
         where MySQL stores its data. However, we never ran a `docker volume create` command. Docker recognizes we want
         to use a named volume and creates one automatically for us.
+        
+    !!! info "Troubleshooting"
+        If you see a `docker: no matching manifest` error, it's because you're trying to run the container in a different
+        architecture than amd64, which is the only supported architecture for the mysql image at the moment. To solve this
+        add the flag --platform linux/amd64 in the previous command
 
 1. To confirm we have the database up and running, connect to the database and verify it connects.
 

From f390971d25a81246815253ca6a266dc654f0e2b7 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Ant=C3=B3nio=20Alvarenga?= <antonioalvarengavd@gmail.com>
Date: Fri, 7 May 2021 11:31:51 +0100
Subject: [PATCH 06/20] enclose code block in backticks

---
 docs/tutorial/multi-container-apps/index.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/docs/tutorial/multi-container-apps/index.md b/docs/tutorial/multi-container-apps/index.md
index 3781ef16..a8bd124e 100644
--- a/docs/tutorial/multi-container-apps/index.md
+++ b/docs/tutorial/multi-container-apps/index.md
@@ -70,7 +70,7 @@ For now, we will create the network first and attach the MySQL container at star
     !!! info "Troubleshooting"
         If you see a `docker: no matching manifest` error, it's because you're trying to run the container in a different
         architecture than amd64, which is the only supported architecture for the mysql image at the moment. To solve this
-        add the flag --platform linux/amd64 in the previous command
+        add the flag `--platform linux/amd64 in the previous command
 
 1. To confirm we have the database up and running, connect to the database and verify it connects.
 

From 958126d5a7fff54b19bea9c6672ba382d1b099dc Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Ant=C3=B3nio=20Alvarenga?= <antonioalvarengavd@gmail.com>
Date: Fri, 7 May 2021 11:33:02 +0100
Subject: [PATCH 07/20] add backtick

---
 docs/tutorial/multi-container-apps/index.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/docs/tutorial/multi-container-apps/index.md b/docs/tutorial/multi-container-apps/index.md
index a8bd124e..9742a192 100644
--- a/docs/tutorial/multi-container-apps/index.md
+++ b/docs/tutorial/multi-container-apps/index.md
@@ -70,7 +70,7 @@ For now, we will create the network first and attach the MySQL container at star
     !!! info "Troubleshooting"
         If you see a `docker: no matching manifest` error, it's because you're trying to run the container in a different
         architecture than amd64, which is the only supported architecture for the mysql image at the moment. To solve this
-        add the flag `--platform linux/amd64 in the previous command
+        add the flag `--platform linux/amd64` in the previous command
 
 1. To confirm we have the database up and running, connect to the database and verify it connects.
 

From 8dd3914433c68370a04f3b6dc7cb2fa941e9acc7 Mon Sep 17 00:00:00 2001
From: Amogh Sahasrabhojanee <amogh@quintype.com>
Date: Sat, 8 May 2021 10:50:38 +0530
Subject: [PATCH 08/20] fix: path to db file in test

---
 app/spec/persistence/sqlite.spec.js | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/app/spec/persistence/sqlite.spec.js b/app/spec/persistence/sqlite.spec.js
index 7b844667..996d4515 100644
--- a/app/spec/persistence/sqlite.spec.js
+++ b/app/spec/persistence/sqlite.spec.js
@@ -1,5 +1,6 @@
 const db = require('../../src/persistence/sqlite');
 const fs = require('fs');
+const location = process.env.SQLITE_DB_LOCATION || '/etc/todos/todo.db';
 
 const ITEM = {
     id: '7aef3d7c-d301-4846-8358-2a91ec9d6be3',
@@ -8,8 +9,8 @@ const ITEM = {
 };
 
 beforeEach(() => {
-    if (fs.existsSync('/etc/todos/todo.db')) {
-        fs.unlinkSync('/etc/todos/todo.db');
+    if (fs.existsSync(location)) {
+        fs.unlinkSync(location);
     }
 });
 

From 9950c06246acfd3224b14542a69c363bc55abcf6 Mon Sep 17 00:00:00 2001
From: Chuli jimmi Manurung <jimmi.ext@gmail.com>
Date: Sun, 13 Jun 2021 21:07:13 +0800
Subject: [PATCH 09/20] docs: Fix missing container id

---
 docs/tutorial/persisting-our-data/index.md | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

diff --git a/docs/tutorial/persisting-our-data/index.md b/docs/tutorial/persisting-our-data/index.md
index fcc772c9..19bdcfa4 100644
--- a/docs/tutorial/persisting-our-data/index.md
+++ b/docs/tutorial/persisting-our-data/index.md
@@ -54,7 +54,10 @@ What you'll see is that the files created in one container aren't available in a
     And look! There's no `data.txt` file there! That's because it was written to the scratch space for
     only the first container.
 
-1. Go ahead and remove the first container using the `docker rm -f` command.
+1. Go ahead and remove the first container using the `docker rm -f <container-id>` command.
+    ```bash
+    docker rm -f <container-id>
+    ```
 
 ## Container Volumes
 
@@ -91,7 +94,7 @@ Every time you use the volume, Docker will make sure the correct data is provide
     docker volume create todo-db
     ```
 
-1. Stop the todo app container once again in the Dashboard (or with `docker rm -f <id>`), as it is still running without using the persistent volume.
+1. Stop the todo app container once again in the Dashboard (or with `docker rm -f <container-id>`), as it is still running without using the persistent volume.
 
 1. Start the todo app container, but add the `-v` flag to specify a volume mount. We will use the named volume and mount
    it to `/etc/todos`, which will capture all files created at the path.
@@ -105,7 +108,7 @@ Every time you use the volume, Docker will make sure the correct data is provide
     Items added to todo list{: style="width: 55%; " }
     {: .text-center }
 
-1. Remove the container for the todo app. Use the Dashboard or `docker ps` to get the ID and then `docker rm -f <id>` to remove it.
+1. Remove the container for the todo app. Use the Dashboard or `docker ps` to get the ID and then `docker rm -f <container-id>` to remove it.
 
 1. Start a new container using the same command from above.
 

From 06d835a3cdc3db0cc6855f8c1d3fbd92071cb87f Mon Sep 17 00:00:00 2001
From: Paul Hermans <mail@paulhermans.eu>
Date: Mon, 12 Jul 2021 16:34:43 +0200
Subject: [PATCH 10/20] Update package.json

sqlite3 version update needed
---
 app/package.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/app/package.json b/app/package.json
index 7465cd04..ca5a7bdf 100644
--- a/app/package.json
+++ b/app/package.json
@@ -12,7 +12,7 @@
     "body-parser": "^1.19.0",
     "express": "^4.17.1",
     "mysql": "^2.17.1",
-    "sqlite3": "^4.1.0",
+    "sqlite3": "^5.0.0",
     "uuid": "^3.3.3",
     "wait-port": "^0.2.2"
   },

From 67e75bb1cb6be1145b288fa884c06462adaa69f8 Mon Sep 17 00:00:00 2001
From: Ngoc Hoang <zuccamia@gmail.com>
Date: Wed, 11 Aug 2021 21:49:23 +0900
Subject: [PATCH 11/20] Update reference links in docker compose section.

---
 docs/tutorial/using-docker-compose/index.md | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/docs/tutorial/using-docker-compose/index.md b/docs/tutorial/using-docker-compose/index.md
index 9927500c..5bcc0f2a 100644
--- a/docs/tutorial/using-docker-compose/index.md
+++ b/docs/tutorial/using-docker-compose/index.md
@@ -102,8 +102,8 @@ docker run -dp 3000:3000 `
 
 
 1. Let's migrate the `-p 3000:3000` part of the command by defining the `ports` for the service. We will use the
-   [short syntax](https://docs.docker.com/compose/compose-file/#short-syntax-1) here, but there is also a more verbose 
-   [long syntax](https://docs.docker.com/compose/compose-file/#long-syntax-1) available as well.
+   [short syntax](https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-1) here, but there is also a more verbose 
+   [long syntax](https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-1) available as well.
 
     ```yaml hl_lines="7 8"
     version: "3.7"
@@ -117,7 +117,7 @@ docker run -dp 3000:3000 `
     ```
 
 1. Next, we'll migrate both the working directory (`-w /app`) and the volume mapping (`-v "$(pwd):/app"`) by using
-   the `working_dir` and `volumes` definitions. Volumes also has a [short](https://docs.docker.com/compose/compose-file/#short-syntax-3) and [long](https://docs.docker.com/compose/compose-file/#long-syntax-3) syntax.
+   the `working_dir` and `volumes` definitions. Volumes also has a [short](https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3) and [long](https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-3) syntax.
 
     One advantage of Docker Compose volume definitions is we can use relative paths from the current directory.
 
@@ -197,7 +197,7 @@ docker run -d `
 1. Next, we'll define the volume mapping. When we ran the container with `docker run`, the named volume was created
    automatically. However, that doesn't happen when running with Compose. We need to define the volume in the top-level
    `volumes:` section and then specify the mountpoint in the service config. By simply providing only the volume name,
-   the default options are used. There are [many more options available](https://docs.docker.com/compose/compose-file/#volume-configuration-reference) though.
+   the default options are used. There are [many more options available](https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference) though.
 
     ```yaml hl_lines="8 9 10 11 12"
     version: "3.7"

From ac4adc866556d17d1d8bd255bb904634621e5dad Mon Sep 17 00:00:00 2001
From: "dependabot[bot]" <49699333+dependabot[bot]@users.noreply.github.com>
Date: Thu, 12 Aug 2021 01:58:18 +0000
Subject: [PATCH 12/20] Bump path-parse from 1.0.6 to 1.0.7 in /app

Bumps [path-parse](https://github.com/jbgutierrez/path-parse) from 1.0.6 to 1.0.7.
- [Release notes](https://github.com/jbgutierrez/path-parse/releases)
- [Commits](https://github.com/jbgutierrez/path-parse/commits/v1.0.7)

---
updated-dependencies:
- dependency-name: path-parse
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>
---
 app/yarn.lock | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/app/yarn.lock b/app/yarn.lock
index 7d934afc..d3ac6a0e 100644
--- a/app/yarn.lock
+++ b/app/yarn.lock
@@ -3178,9 +3178,9 @@ path-key@^2.0.0, path-key@^2.0.1:
   integrity sha1-QRyttXTFoUDTpLGRDUDYDMn0C0A=
 
 path-parse@^1.0.6:
-  version "1.0.6"
-  resolved "https://registry.yarnpkg.com/path-parse/-/path-parse-1.0.6.tgz#d62dbb5679405d72c4737ec58600e9ddcf06d24c"
-  integrity sha512-GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==
+  version "1.0.7"
+  resolved "https://registry.yarnpkg.com/path-parse/-/path-parse-1.0.7.tgz#fbc114b60ca42b30d9daf5858e4bd68bbedb6735"
+  integrity sha512-LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==
 
 path-to-regexp@0.1.7:
   version "0.1.7"

From 433353af1c46e08d330a5e3dbe4872df9ed712f5 Mon Sep 17 00:00:00 2001
From: Oliver Howell <89071729+ollyhowell@users.noreply.github.com>
Date: Tue, 14 Sep 2021 15:39:14 +0100
Subject: [PATCH 13/20] Add reminder to save file for the app refresh

---
 docs/tutorial/using-bind-mounts/index.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/docs/tutorial/using-bind-mounts/index.md b/docs/tutorial/using-bind-mounts/index.md
index 29138b81..13557fb0 100644
--- a/docs/tutorial/using-bind-mounts/index.md
+++ b/docs/tutorial/using-bind-mounts/index.md
@@ -78,7 +78,7 @@ So, let's do it!
     When you're done watching the logs, exit out by hitting `Ctrl`+`C`.
 
 1. Now, let's make a change to the app. In the `src/static/js/app.js` file, let's change the "Add Item" button to simply say
-   "Add". This change will be on line 109.
+   "Add". This change will be on line 109 - remember to save the file.
 
     ```diff
     -                         {submitting ? 'Adding...' : 'Add Item'}

From 4e7c2668fc9d11f903a22bf09e3ea0903064f310 Mon Sep 17 00:00:00 2001
From: "dependabot[bot]" <49699333+dependabot[bot]@users.noreply.github.com>
Date: Tue, 21 Sep 2021 18:15:16 +0000
Subject: [PATCH 14/20] Bump tmpl from 1.0.4 to 1.0.5 in /app

Bumps [tmpl](https://github.com/daaku/nodejs-tmpl) from 1.0.4 to 1.0.5.
- [Release notes](https://github.com/daaku/nodejs-tmpl/releases)
- [Commits](https://github.com/daaku/nodejs-tmpl/commits/v1.0.5)

---
updated-dependencies:
- dependency-name: tmpl
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>
---
 app/yarn.lock | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/app/yarn.lock b/app/yarn.lock
index 7d934afc..f0fc0098 100644
--- a/app/yarn.lock
+++ b/app/yarn.lock
@@ -3981,9 +3981,9 @@ timed-out@^4.0.0:
   integrity sha1-8y6srFoXW+ol1/q1Zas+2HQe9W8=
 
 tmpl@1.0.x:
-  version "1.0.4"
-  resolved "https://registry.yarnpkg.com/tmpl/-/tmpl-1.0.4.tgz#23640dd7b42d00433911140820e5cf440e521dd1"
-  integrity sha1-I2QN17QtAEM5ERQIIOXPRA5SHdE=
+  version "1.0.5"
+  resolved "https://registry.yarnpkg.com/tmpl/-/tmpl-1.0.5.tgz#8683e0b902bb9c20c4f726e3c0b69f36518c07cc"
+  integrity sha512-3f0uOEAQwIqGuWW2MVzYg8fV/QNnc/IpuJNG837rLuczAaLVHslWHZQj4IGiEl5Hs3kkbhwL9Ab7Hrsmuj+Smw==
 
 to-fast-properties@^2.0.0:
   version "2.0.0"

From 8a8994297d6076a74a590c765663d679c59b6f62 Mon Sep 17 00:00:00 2001
From: magusikrak <sugamkarki7058@gmail.com>
Date: Wed, 29 Sep 2021 00:09:39 +0545
Subject: [PATCH 15/20] removed bodyparser as a dependency

---
 app/package.json | 1 -
 app/src/index.js | 2 +-
 2 files changed, 1 insertion(+), 2 deletions(-)

diff --git a/app/package.json b/app/package.json
index 7465cd04..b6094967 100644
--- a/app/package.json
+++ b/app/package.json
@@ -9,7 +9,6 @@
     "dev": "nodemon src/index.js"
   },
   "dependencies": {
-    "body-parser": "^1.19.0",
     "express": "^4.17.1",
     "mysql": "^2.17.1",
     "sqlite3": "^4.1.0",
diff --git a/app/src/index.js b/app/src/index.js
index 3bd39068..7e8e7720 100644
--- a/app/src/index.js
+++ b/app/src/index.js
@@ -6,7 +6,7 @@ const addItem = require('./routes/addItem');
 const updateItem = require('./routes/updateItem');
 const deleteItem = require('./routes/deleteItem');
 
-app.use(require('body-parser').json());
+app.use(express.json());
 app.use(express.static(__dirname + '/static'));
 
 app.get('/items', getItems);

From acdcd83ced646b844d289811313c5f49ad592634 Mon Sep 17 00:00:00 2001
From: Spencer Adolph <46459660+spenceradolph@users.noreply.github.com>
Date: Thu, 21 Oct 2021 12:57:36 -0500
Subject: [PATCH 16/20] Removed 'RUN apk add --no-cache python g++ make'

This line did not appear to be necessary for the tutorial. Testing with it removed appeared to have no effect. Additionally, this line does not appear later in the tutorial when referring back to this step (see /docs/tutorial/image-building-best-practices/index.md).
---
 docs/tutorial/our-application/index.md | 1 -
 1 file changed, 1 deletion(-)

diff --git a/docs/tutorial/our-application/index.md b/docs/tutorial/our-application/index.md
index a6a3fe4f..fceca1f2 100644
--- a/docs/tutorial/our-application/index.md
+++ b/docs/tutorial/our-application/index.md
@@ -38,7 +38,6 @@ see a few flaws in the Dockerfile below. But, don't worry! We'll go over them.
 
     ```dockerfile
     FROM node:12-alpine
-    RUN apk add --no-cache python g++ make
     WORKDIR /app
     COPY . .
     RUN yarn install --production

From d002206c3e73171721d2b7616cf2d9c0afddcd6c Mon Sep 17 00:00:00 2001
From: Stefan Scherer <stefan.scherer@docker.com>
Date: Wed, 10 Nov 2021 09:17:07 +0100
Subject: [PATCH 17/20] Make getting started guide faster

Signed-off-by: Stefan Scherer <stefan.scherer@docker.com>
---
 Dockerfile | 14 +++++++++-----
 1 file changed, 9 insertions(+), 5 deletions(-)

diff --git a/Dockerfile b/Dockerfile
index 60fce0c2..4b43f6db 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -5,20 +5,24 @@ WORKDIR /app
 COPY requirements.txt .
 RUN pip install -r requirements.txt
 
-# Run tests to validate app
 FROM node:12-alpine AS app-base
-RUN apk add --no-cache python g++ make
 WORKDIR /app
 COPY app/package.json app/yarn.lock ./
-RUN yarn install
 COPY app/spec ./spec
 COPY app/src ./src
+
+# Run tests to validate app
+FROM app-base AS test
+RUN apk add --no-cache python3 g++ make
+RUN yarn install
 RUN yarn test
 
 # Clear out the node_modules and create the zip
 FROM app-base AS app-zip-creator
-RUN rm -rf node_modules && \
-    apk add zip && \
+COPY app/package.json app/yarn.lock ./
+COPY app/spec ./spec
+COPY app/src ./src
+RUN apk add zip && \
     zip -r /app.zip /app
 
 # Dev-ready container - actual files will be mounted in

From 782d9421aef5f0a77d56c87478cfa5f31f4f05b6 Mon Sep 17 00:00:00 2001
From: Stefan Scherer <stefan.scherer@docker.com>
Date: Wed, 10 Nov 2021 09:17:28 +0100
Subject: [PATCH 18/20] Add dependencies for Apple silicon / M1 / arm64 builds

Signed-off-by: Stefan Scherer <stefan.scherer@docker.com>
---
 docs/tutorial/our-application/index.md | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/docs/tutorial/our-application/index.md b/docs/tutorial/our-application/index.md
index fceca1f2..cb2747f8 100644
--- a/docs/tutorial/our-application/index.md
+++ b/docs/tutorial/our-application/index.md
@@ -38,6 +38,8 @@ see a few flaws in the Dockerfile below. But, don't worry! We'll go over them.
 
     ```dockerfile
     FROM node:12-alpine
+    # Adding build tools to make yarn install work on Apple silicon / arm64 machines
+    RUN apk add --no-cache python3 g++ make
     WORKDIR /app
     COPY . .
     RUN yarn install --production

From 6086449d1590e29dc4188d2b4019fbb320c12794 Mon Sep 17 00:00:00 2001
From: "dependabot[bot]" <49699333+dependabot[bot]@users.noreply.github.com>
Date: Fri, 12 Nov 2021 07:04:04 +0000
Subject: [PATCH 19/20] Bump mkdocs from 1.2.2 to 1.2.3

Bumps [mkdocs](https://github.com/mkdocs/mkdocs) from 1.2.2 to 1.2.3.
- [Release notes](https://github.com/mkdocs/mkdocs/releases)
- [Commits](https://github.com/mkdocs/mkdocs/compare/1.2.2...1.2.3)

---
updated-dependencies:
- dependency-name: mkdocs
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>
---
 requirements.txt | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/requirements.txt b/requirements.txt
index 12365e90..2bd1b6eb 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,4 @@
-mkdocs==1.2.2
+mkdocs==1.2.3
 mkdocs-material==4.6.3
 mkdocs-minify-plugin==0.2.3
 pygments==2.7.4

From 5c1574e6432b4e8d25b46a4934a7cc568403366a Mon Sep 17 00:00:00 2001
From: SosukeHosokawa <so298go@gmail.com>
Date: Wed, 24 Nov 2021 01:24:18 +0900
Subject: [PATCH 20/20] fix on 'Our application' tutorial for Apple silicon

---
 docs/tutorial/our-application/index.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/docs/tutorial/our-application/index.md b/docs/tutorial/our-application/index.md
index cb2747f8..28145346 100644
--- a/docs/tutorial/our-application/index.md
+++ b/docs/tutorial/our-application/index.md
@@ -39,7 +39,7 @@ see a few flaws in the Dockerfile below. But, don't worry! We'll go over them.
     ```dockerfile
     FROM node:12-alpine
     # Adding build tools to make yarn install work on Apple silicon / arm64 machines
-    RUN apk add --no-cache python3 g++ make
+    RUN apk add --no-cache python2 g++ make
     WORKDIR /app
     COPY . .
     RUN yarn install --production

**Comment by Darkdeath-2** [comment]
N

**Comment by Terafugia** [comment]
Something something..

**Pull request closed without merging**
