### PR TITLE
Bump y18n from 4.0.0 to 4.0.1 in /app

### PR DESCRIPTION
**Pull request by Tjolk072**
Bumps [y18n](https://github.com/yargs/y18n) from 4.0.0 to 4.0.1.
- [Release notes](https://github.com/yargs/y18n/releases)
- [Changelog](https://github.com/yargs/y18n/blob/master/CHANGELOG.md)
- [Commits](https://github.com/yargs/y18n/commits)

Signed-off-by: dependabot[bot] <support@github.com>

### CODE REVIEW

**Comment by Tjolk072** [comment]
Bump in app #136

**Comment by Tjolk072** [comment]
Changes in Pull Request #136

**Comment by Tjolk072** [comment]
Modified to version "4.0.1".

**Comment by Tjolk072** [comment]
Changes in Pull Request #136.

**Comment by StefanScherer** [comment]
Thanks @Tjolk072, but I’ll close this PR in favor of #135

**Pull request closed without merging**
